name: Add Label
on:
    pull_request:
        types:
            - opened
jobs:
    add-label:
        name: Add Label
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write
            contents: write
            issues: read
        steps:
            - uses: actions/checkout@v4.2.2
            - uses: delivery-much/actions-assigner@v1.0.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: christianvuerings/add-labels@v1.1
              with:
                  labels: |
                      Missing dev review
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
