name: Auto-assign Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required permission to modify repository contents
    steps:
      - name: Add issue to GitHub project
        uses: actions/github-script@v6
        with:
          script: |
            const repoOwner = 'Satellite-im';  // Repository owner (Organization or User)
            const repoName = 'UplinkWeb';  // Replace with the repository name
            const projectNumber = 19;  // The number of the project you want to add issues to
            const issueId = context.payload.issue.node_id;  // The issue ID from the event payload

            // GraphQL query to get the project ID from the repository
            const { repository } = await github.graphql(`
              query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                  projectV2(number: $number) {
                    id
                  }
                }
              }
            `, {
              owner: repoOwner,
              repo: repoName,
              number: projectNumber
            });

            const projectId = repository.projectV2.id;  // Extract the project ID

            // Mutation to add the issue to the project
            await github.graphql(`
              mutation($projectId: ID!, $issueId: ID!) {
                addProjectV2ItemById(input: { projectId: $projectId, contentId: $issueId }) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              issueId: issueId
            });
