name: Automated Tests

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]
        paths-ignore:
            - ".github/workflows/**"
            - "!.github/workflows/automated-tests.yml"
            - ".gitignore"
            - ".prettierrc.json"
            - "PULL_REQUEST_TEMPLATE.md"
            - "README.md"

jobs:
    cypress-run:
        runs-on: macos-latest
        steps:
            - name: Checkout Uplink Web directory 🔖
              uses: actions/checkout@v4

            - name: Checkout Automated Tests directory 🔖
              uses: actions/checkout@v4
              with:
                  repository: Satellite-im/automated-tests-web
                  path: automated-tests

            - name: Setup Node.js for Uplink Web 🔨
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install NPM dependencies for Uplink Web 📦
              run: npm install

            - name: Install NPM dependencies for Testing Repo 📦
              working-directory: automated-tests
              run: npm install

            - name: Run server
              run: npm run dev &

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  wait-on: "http://localhost:5173/"
                  working-directory: automated-tests
                  browser: chrome

            - name: Upload screenshots and videos from failed tests 📷
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-artifacts
                  path: |
                      automated-tests/cypress/screenshots
                      automated-tests/cypress/videos

    playwright-run:
        timeout-minutes: 60
        runs-on: macos-latest
        permissions:
            checks: write
            pull-requests: write
            contents: write
            issues: read
        steps:
            - name: Checkout Uplink Web directory 🔖
              uses: actions/checkout@v4

            - name: Checkout Automated Tests directory 🔖
              uses: actions/checkout@v4
              with:
                  repository: Satellite-im/automated-tests-web
                  path: automated-tests

            - name: Setup Node.js for Uplink Web 🔨
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies for Uplink Web 📦
              run: npm install

            - name: Install dependencies for Testing Repo 📦
              working-directory: automated-tests
              run: npm install

            - name: Install Playwright Browsers
              working-directory: automated-tests
              run: npx playwright install --with-deps

            - name: Run server for Uplink Web
              run: npm run dev &

            - name: Run Playwright tests
              working-directory: automated-tests
              run: npx playwright test

            - name: Copy json report to root directory
              run: cp ./automated-tests/playwright-report/report.json ./report.json

            - uses: daun/playwright-report-summary@v3
              if: always()
              with:
                  github-token: ${{ secrets.github_token }}
                  report-file: ./report.json
                  job-summary: false
                  comment-title: "Automated Test Results"

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: automated-tests/playwright-report/
                  retention-days: 5
