name: Auto-add Issues to Project

on:
    issues:
        types: [opened, edited]

jobs:
    add_to_project:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2

            # Set up GitHub CLI
            - name: Install GitHub CLI
              run: sudo apt-get install gh -y

            # Authenticate using the PAT instead of GITHUB_TOKEN
            - name: Authenticate GitHub CLI
              run: gh auth login --with-token <<< "$PAT"
              env:
                  PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            # Add Issue to Project (Replace with the correct slug)
            - name: Add Issue to Project
              run: gh project item-add --project "Satellite-im/UplinkWeb" --url "${{ github.event.issue.html_url }}"
              env:
                  PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
