name: Auto-add Issues to Project

on:
    issues:
        types: [opened]

jobs:
    add_to_project:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2

            # Set up GitHub CLI
            - name: Install GitHub CLI
              run: sudo apt-get install gh -y

            # Authenticate using the GITHUB_TOKEN
            - name: Authenticate GitHub CLI
              run: gh auth login --with-token <<< "$GITHUB_TOKEN"

            # Add Issue to Project
            - name: Add Issue to Project
              run: gh project item-add --project "19" --url "${{ github.event.issue.html_url }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
