name: Build MacOS Release
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-macos-release:
        permissions: write-all
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4.2.0

            - name: setup node
              uses: actions/setup-node@v4.0.4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: install frontend dependencies
              run: npm install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  APPLE_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
                  APPLE_SIGNING_IDENTITY: ${{ secrets.MACOS_CERTIFICATE_NAME }}
                  APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
                  APPLE_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
                  APPLE_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}

            - name: Upload signed macOS Installer
              uses: actions/upload-artifact@v4.4.0
              with:
                  name: build-macos-official
                  path: src-tauri/target/release/bundle/dmg/*.dmg
                  retention-days: 5
