name: Build MacOS Release
on:
    pull_request: # this is only temporarily for testing the action
        types: [opened, synchronize, reopened, edited] # this is only temporarily for testing the action
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-macos-release:
        permissions: write-all
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4.2.0

            - name: setup node
              uses: actions/setup-node@v4.0.4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: install frontend dependencies
              run: npm install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Codesign and Build executable MacOS
              continue-on-error: true
              env:
                  MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
                  MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
                  MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
                  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
                  MACOS_KEYCHAIN_NAME: ${{ secrets.MACOS_KEYCHAIN_NAME }}
                  MACOS_CERT_ID: ${{secrets.MACOS_CERT_ID}}
              run: |
                  echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
                  security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" builduplink.keychain
                  security default-keychain -s builduplink.keychain
                  security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" builduplink.keychain
                  security set-keychain-settings builduplink.keychain
                  security import certificate.p12 -k builduplink.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" builduplink.keychain
                  security find-identity -p codesigning -v
                  security list-keychains
                  codesign --deep --force --verify --verbose --sign "$MACOS_CERT_ID" ./src-tauri/target/release/bundle/macos/*.app
                  codesign --deep --force --verify --verbose --sign "$MACOS_CERT_ID" ./src-tauri/target/release/bundle/dmg/*.dmg

            - name: "Notarize executable MacOS"
              env:
                  PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
                  PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
                  PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
                  MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
              run: |
                  echo "Create keychain profile"
                  xcrun notarytool store-credentials "uplink-notarytool-profile" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
                  echo "Creating temp notarization archive"
                  ditto -c -k --keepParent "src-tauri/target/release/bundle/macos/Uplink.app" "notarization.zip"
                  echo "Notarize app"
                  xcrun notarytool submit "notarization.zip" --keychain-profile "uplink-notarytool-profile" --wait
                  echo "Attach staple"
                  xcrun stapler staple "src-tauri/target/release/bundle/macos/Uplink.app"

            - name: Create ZIP archive MacOS
              run: |
                  ditto -c -k --sequesterRsrc --keepParent src-tauri/target/release/bundle/macos/Uplink.app Uplink-Mac-Universal.zip

            - name: Calculate hashes MacOS
              run: |
                  shasum -a 256 Uplink-Mac-Universal.zip > Uplink-Mac-Universal.zip.sha256.txt

            - name: Upload signed macOS Installer
              uses: actions/upload-artifact@v4.4.0
              with:
                  name: build-macos-official
                  path: src-tauri/target/release/bundle/macos/Uplink-Mac-Universal.zip
                  retention-days: 5
