name: GitHub Pages

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
    contents: write

jobs:
  github_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Deploy to GitHub Pages
        id: gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
