name: Remove All Labels

on:
    pull_request:
        types: [closed]

jobs:
    remove_labels:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            pull-requests: write
            contents: write
            issues: read
        steps:
            - uses: actions/checkout@v4
            - uses: rogerluan/label-remover@v1.0.1
              with:
                  github_token: ${{ secrets.github_token }}
